services:
  mongo:
    image: mongo:7
    volumes:
      - Devices_Data:/data/db
    # порты можно не пробрасывать, если API в том же compose
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - Database__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo
volumes:
  Devices_Data:
    name: Devices_Data 
