server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass http://api:8080/;   # имя сервиса api
        proxy_set_header Host $host;
    }
    location = /login {
        rewrite ^ /Login/login.html break;
    }
    location = /main {
        rewrite ^ /Main/main.html break;
    }
    location / {
        try_files $uri $uri/ =404;
    }
}